### ISSUE TITLE
Live reload doesn't work on Windows

### ISSUE THREAD

**Issue by Bolderaysky** [cjnix35/overload-js#16]
## Issue
On Linux, **preview** supports Live Reload future. That means, every time, when you change your frontend and save it, app will update itself without restarting it or clicking right mouse button and select 'reload'. On Windows, this feature can be compiled, but do absolutely nothing.
## How this can be solved?
This can be solved by replacing filesystem watcher lib that is currently in use by some another library that can do the job. Also, it can be solved by using native libraries to handle filesystem events, but this is bad solution, because it's quite difficult to guarantee that all features will be available on all operating systems. Also this needs a lot of testing, so it's not an option for devs. If someone can help to solve this issue, please, fork project, make your changes and open a pull request, or, at least, write below what can be done to solve this.

**Comment by cjnix35** [comment]
Issue solved by implementing hot reloading via webpack-dev-server and React Fast Refresh Plugin.
Also filesystem watcher will be removed and the architecture will be redesigned.

**Comment by cjnix35** [comment]
Issue solved by implementing hot reloading via webpack-dev-server and React Fast Refresh Plugin.
Also filesystem watcher will be removed and the architecture will be redesigned.
